### PR TITLE
Add favicon.ico

### PR DESCRIPTION
**Pull request by Codycody31**
Just adds a `favicon.ico` to the public folder so that we actually have the icon in the browser tab.

### CODE REVIEW

**Comment by noClaps** [comment]
Which platform are you on? [Most platforms](https://caniuse.com/link-icon-png) support PNG favicons, and there's already a PNG favicon. There's a chance that you might have to clear your browser cache and reload the page for the favicon to appear.

**Comment by Codycody31** [comment]
This is for Firefox, I don't believe it uses the favicon.png like other browsers

**Comment by Codycody31** [comment]
Hmm. png's are supported, guess this is unneeded

**Comment by noClaps** [comment]
Ah, I think I see the issue. It's not that Firefox doesn't support PNG favicons, it's that there's no `<link>` tag for the favicon in the `<head>`. This doesn't seem to cause an issue in Safari, but it seems to not load the favicon on Firefox, and on Chrome on Android either. Should be a simple fix of [adding the head config](https://vitepress.dev/reference/site-config#head).

**Pull request closed without merging**
